#!/bin/bash

# ========================================
# SUGRS - Quick Start Commands
# ========================================
# Copy and paste these commands into your terminal

echo "🏛️ SUGRS - Smart Urban Grievance Resolution System"
echo "=================================================="
echo ""
echo "STEP 1: Start MongoDB (choose ONE)"
echo ""
echo "Option A - Docker (Recommended):"
echo "  docker run -d --name mongodb -p 27017:27017 mongo:latest"
echo ""
echo "Option B - Homebrew (macOS):"
echo "  brew tap mongodb/brew"
echo "  brew install mongodb-community"
echo "  brew services start mongodb-community"
echo ""
echo "Option C - Interactive Setup:"
echo "  ./setup-mongodb.sh"
echo ""
echo "=================================================="
echo ""
echo "STEP 2: Start the application"
echo ""
echo "From project root (/Users/ayushsarode/Downloads/sugrs):"
echo ""
echo "  npm run start-servers"
echo ""
echo "This will start:"
echo "  • Backend API: http://localhost:8080"
echo "  • Frontend App: http://localhost:5173"
echo ""
echo "=================================================="
echo ""
echo "STEP 3: Login & Test"
echo ""
echo "Open: http://localhost:5173"
echo ""
echo "Test Accounts:"
echo "  Citizen:"
echo "    Email: priya@sugrs.in"
echo "    Password: citizen123"
echo ""
echo "  Officer:"
echo "    Email: rajan@sugrs.in"
echo "    Password: officer123"
echo ""
echo "  Admin:"
echo "    Email: admin@sugrs.in"
echo "    Password: admin123"
echo ""
echo "=================================================="
echo ""
echo "Useful Commands:"
echo "  npm run dev              # Start with hot reload"
echo "  npm run backend          # Backend only"
echo "  npm run frontend         # Frontend only"
echo "  curl http://localhost:8080/api/health  # Test backend"
echo ""
echo "Documentation:"
echo "  • QUICKSTART.md - Get running in 2 minutes"
echo "  • README.md - Complete documentation"
echo "  • SETUP_INSTRUCTIONS.md - Detailed setup guide"
echo ""
echo "=================================================="
echo ""
echo "Ready to go! 🚀"

